Title: Allelic specific expression 
========================================================
# call SNPs between 414 & 415 F1 population 
```{r} 
# 1) trim & map fastq file using script trimming_mapping_01_23_2017.sh 

# 2) merge bam files from biological replicates 

# 3) extract uniquely mapped file, sort, and convert to bam file 

# 4) call SNPs for each tissue type seperately, include Da-Ae & Da-Ol 

# 5) filter to remove indel & keep biallelic SNPs only
# https://github.com/leejimmy93/KIAT/blob/master/F1/filter_SNP_biallelic_QUAL.sh
```

# load libraries 
```{r}
library(vcfR)
source("~/KIAT/F1/helpler.R")  
```

# examine F1 dataset to study gene imprinting effect 
```{r}
# ./process_vcf.sh input.vcf input_modified.vcf # to make the right format of vcf file 
F1.young <- read.vcfR("~/F1_SNP/vcf/with_GQ/F1_young_filtered.recode.vcf")  
F1.young.reform <- reform.vcf.F1(temp=F1.young)
dim(F1.young.reform) # 1247960      16 
save(F1.young.refom, file="~/F1_SNP/output/F1.young.reform.Rdata")
```

# filter based on missing data (no missing data), GQ (>30 in each sample), DP (>10 in each sample)  
```{r} 
load("~/F1_SNP/output/F1.young.reform.Rdata")

# 1) filter based on missing data 
F1.young.nomissing <- F1.young.reform[complete.cases(F1.young.reform),]
dim(F1.young.nomissing) # 635218     16 

# 2) transform filter columns to numeric values 
F1.young.nomissing[,(5:16)] <- lapply(F1.young.nomissing[,(5:16)], function(x) as.numeric(as.character(x))) 

# 3) filter based on GQ  
F1.young.GQ.filtered <- GQ.filter(vcf=F1.young.nomissing, n=30)
dim(F1.young.GQ.filtered) # 288085     16  

hist(as.numeric(as.character(F1.young.GQ.filtered$F1_415_GQ)))

# 4) filter based depth 
F1.young.DP.filtered <- DP.filter(vcf=F1.young.GQ.filtered, n=10)
dim(F1.young.DP.filtered) # 166691     16 

# 5) filter based on gt (homozygous in parents)
F1.young.GQ.filtered <- subset(F1.young.DP.filtered, (((Ae_GT=="-1" & Ol_GT=="1")) | ((Ae_GT=="1" & Ol_GT=="-1"))))
dim(F1.young.GQ.filtered) # 49140    16 

save(F1.young.GQ.filtered, file = "~/F1_SNP/output/F1.young.GQ.filtered.Rdata")
```




 

