---
title: "eQTL_batch_corrected_flipped_C05C08"
output: html_document
---

Goal of this script is to re-run eQTL analysis using reconstructed map with C05 and C08 modified 

### import lib
```{r} 
library(tidyverse) 
library(qtl)
library(snowfall) 
library(Biostrings) 
source("~/KIAT/function_BnRNAseq.R")    
```

### scanone 

### with flipped LG for eQTL anlaysis just for the plot 

```{r}
cross.F2 <- read.cross("csvsr", genfile ="~/F2/data/QTL_analysis/LG.f2.madmapper.final_gen_revised_flipped_C05C08.csv", 
                         phefile = "~/F2/output/network_analysis/vstMat.f2.batch.corrected_revised.csv",
                         genotypes = c("AA", "AB", "BB"))   # although the sample IDs are not matched in the original phe and gen file, I still get the right result. 

cross.F2 <- sim.geno(cross.F2,step=1,n.draws=32) # imputation?  
cross.F2 <- calc.genoprob(cross.F2,step=1) 

# before real analysis, test one gene 
tmp <- which(colnames(cross.F2$pheno) %in% "BnaA08g11140D")  
test <- scanone(cross.F2, pheno.col = tmp,method = "imp", use = "all.obs")
plot(test) # looks right 

scanone_eQTL.F2 <- scanone(cross.F2, pheno.col = 2:ncol(cross.F2$pheno), 
	         method = "imp", use = "all.obs")  

### permutation...  
set.seed(12345)   
permtest.F2 <- scanone(cross.F2, pheno.col = 2, method = "imp", n.perm = 10000)  

alphas <- seq(0.01, 0.10, by = 0.01) 
lod.thrs <- summary(permtest.F2, alphas) 
lod.thrs   

save(cross.F2, scanone_eQTL.F2, permtest.F2, lod.thrs, file = "~/F2/output/eQTL/scanone-eqtl_F2_flipped_C05C08.RData") 
``` 

### determine cis- and trans- eQTL 
```{r}
load("~/F2/output/eQTL/scanone-eqtl_F2_flipped_C05C08.RData")
scanone_eQTL.F2 %>% dim() # 4944 56182 

scanone_eQTL.F2$chr <- as.character(scanone_eQTL.F2$chr) 

# get threshold 
threshold.95 <- lod.thrs[5,] 
threshold.95 # 4.18 

# get all eQTL based on this threshold   
eQTL_sign <- 
sapply(colnames(scanone_eQTL.F2), function(gene) {
  sum(scanone_eQTL.F2[,gene] > threshold.95) > 0 
}) 

sum(eQTL_sign) # 22,695 genes with eQTL 
scanone_eQTL.F2 <- scanone_eQTL.F2[,eQTL_sign]  
dim(scanone_eQTL.F2) # 4944 22695  

# get bayesint result for every gene 
scanone.gather <-  
scanone_eQTL.F2 %>% 
  gather(key = trait, value = LOD, -chr, -pos) 

sig.chrs <- scanone.gather %>% filter(LOD > threshold.95) %>% 
  group_by(trait,chr) %>% 
  dplyr::summarise(count = n()) # this is to get the significant chr ID for each trait 

sig.chrs 
sig.chrs %>% dim() # 26244         3

bayesint.list <- apply(sig.chrs,1,function(hit) { # for every row("trait, chr, count") in eigengene module 
    result <- bayesint(scanone_eQTL.F2[c("chr","pos",hit["trait"])],  
                     chr=hit["chr"], 
                     lodcolumn = 1, 
                     expandtomarkers = TRUE 
  )
  colnames(result)[3] <- "LOD" 
  result
})  

names(bayesint.list) <- sig.chrs$trait

bayesint.list <- lapply(bayesint.list,function(x) 
                          x %>% 
                          as.data.frame() %>%
                          rownames_to_column(var="markername")  %>% # make rownames to column and use "markername" as the colname for the new colomn  
                          mutate(chr=as.character(chr)) 
)  

bayesint.result <- 
as.tibble(bind_rows(bayesint.list,.id="trait")) %>% # combine list into tibble 
    dplyr::select(trait,chr,pos,markername,LOD) %>%  
    separate(markername,into=c("chr1","Mbp"),sep="_", convert=TRUE) %>%  
    group_by(trait,chr) %>% 
    dplyr::summarize(start=min(Mbp, na.rm = T),end=max(Mbp, na.rm = T), pos=median(pos, na.rm = T), min_eQTL_LOD=min(LOD),max_eQTL_LOD=max(LOD), genetic_start=min(pos, na.rm = T), genetic_end=max(pos, na.rm = T)) %>% 
  #for the high QTL peaks the interval width is 0.  That is overly precise and need to widen those.
  # mutate(start=ifelse(start==end, start-20000,start), end=ifelse(start==end,end+20000,end)) 
  mutate(start_modified=ifelse(start-1000000>0, start-1000000, 0), end_modified=end+1000000) 
  

bayesint.result %>% dim() # 26244    11

# get genome range 
library(IRanges)
library(GenomicRanges)
library(GenomicFeatures) 
library("rtracklayer") 

### get gff file with gene chrom & pos info, gff3 file must be sorted 
gff.mRNA <- read.table("~/Reference/B.napus/gff.mRNA")
dim(gff.mRNA) # 101040      4 
head(gff.mRNA) 
colnames(gff.mRNA) <- c("gene_CHROM", "gene_start", "gene_end", "gene_ID") 
gff.mRNA %>% head()  

# look for cis-eQTL 
bayesint.result.2 <- 
bayesint.result %>% 
  mutate(gene_ID = trait, eQTL_chr = chr, eQTL_start = start_modified, eQTL_end = end_modified) %>% 
  dplyr::select(trait, gene_ID, eQTL_chr, pos, eQTL_start, eQTL_end, start, end, min_eQTL_LOD, max_eQTL_LOD, genetic_start, genetic_end) %>% 
  left_join(gff.mRNA, by = "gene_ID") 

bayesint.result.2$eQTL_chr <- paste("chr", bayesint.result.2$eQTL_chr, sep = "")
bayesint.result.2 %>% head()

cis_eQTL <- 
bayesint.result.2 %>% 
  filter(eQTL_chr == gene_CHROM) %>% 
  filter((gene_start < eQTL_start & gene_end > eQTL_start) | # also need SNP pos... 
         (gene_start >= eQTL_start & gene_end <= eQTL_end) |
         (gene_start < eQTL_end & gene_end > eQTL_end)) 

dim(cis_eQTL) # 11587    15

trans_eQTL <- 
bayesint.result.2 %>% 
  anti_join(cis_eQTL) 

save(cis_eQTL, trans_eQTL, file = "~/F2/output/eQTL/cis_trans_result_new_flipped_C05C08.Rdata")
```

### determine cis- and trans- eQTL using lodint 
Also tried with lodint() to get QTL interval, no big difference compared to bayesint() 

```{r} 
library(ggplot2) 
load("~/F2/output/eQTL/cis_trans_result_new_flipped_C05C08.Rdata") 

cis_eQTL %>% dim() # 11587    15
trans_eQTL %>% dim() # 14657    15  

### FAD6
cis_eQTL %>% 
  filter(gene_ID == "BnaA08g12780D") %>% 
  View()
###

cis_eQTL$class <- rep("cis", nrow(cis_eQTL))  
trans_eQTL$class <- rep("trans", nrow(trans_eQTL))   

# get only main chromosome stuff   
eQTL <- rbind(cis_eQTL, trans_eQTL) 
eQTL <- eQTL[grep("random", eQTL$gene_CHROM, value = FALSE, invert = T),] # random scaffolds are exluced 
eQTL$class <- factor(eQTL$class, levels = c("cis", "trans"))
eQTL$gene_CHROM <- gsub("(chr)([[:print:]]+)", "\\2", eQTL$gene_CHROM)
eQTL$eQTL_chr <- gsub("(chr)([[:print:]]+)", "\\2", eQTL$eQTL_chr)
eQTL$gene_CHROM <- factor(eQTL$gene_CHROM, levels = c("C09", "C08", "C07", "C06", "C05", "C04", "C03", "C02", "C01", "A10", "A09", "A08", "A07", "A06", "A05", "A04", "A03", "A02", "A01"))
eQTL$eQTL_chr <- factor(eQTL$eQTL_chr, levels = c("A01", "A02", "A03", "A04", "A05", "A06", "A07", "A08", "A09", "A10", "C01", "C02", "C03", "C04", "C05", "C06", "C07", "C08", "C09"))

# plot out the stuff   
p.eQTL <- 
eQTL %>% 
  ggplot() + 
  geom_point(aes(x = pos, y = gene_start, color = class), size = 0.5) +
  facet_grid(gene_CHROM ~ eQTL_chr, switch = "both", scales = "free") + 
  theme_classic() + 
  theme(panel.spacing = unit(0, "lines"), panel.border = element_rect(colour = "black", fill=NA, size=0.1)) + 
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(), 
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank()) + 
  labs(x = "eQTL genetic position", y = "gene start") + 
  scale_color_manual(values=c("red", "royalblue"))  

p.eQTL      

p.cis_eQTL <-  
eQTL %>% 
  dplyr::filter(class == "cis") %>%
  ggplot() + 
  geom_point(aes(x = pos, y = gene_start), size = 0.5) +
  facet_grid(gene_CHROM ~ eQTL_chr, scales = "free", switch="both") + 
  theme_classic() +
  theme(panel.spacing = unit(0, "lines"), panel.border = element_rect(colour = "black", fill=NA, size=0.1)) +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(), 
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank()) + 
  labs(x = "eQTL genetic position", y = "gene start")

p.cis_eQTL  

p.trans_eQTL <- 
eQTL %>% 
  dplyr::filter(class == "trans") %>%
  ggplot() + 
  geom_point(aes(x = pos, y = gene_start), size = 0.5) + # x is genetic position of eQTL, y is physical start position of gene 
  facet_grid(gene_CHROM ~ eQTL_chr, scales = "free", switch="both") + 
  theme_classic() +
  theme(panel.spacing = unit(0, "lines"), panel.border = element_rect(colour = "black", fill=NA, size=0.1)) +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(), 
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank()) + 
  labs(x = "eQTL genetic position", y = "gene start")   

p.trans_eQTL
ggsave(p.eQTL, filename = "~/F2/output/eQTL/figure/p.eQTL.flipped.png", height = 10, width = 10) 
ggsave(p.cis_eQTL, filename = "~/F2/output/eQTL/figure/p.cis_eQTL.flipped.png", height = 10, width = 10)
ggsave(p.trans_eQTL, filename = "~/F2/output/eQTL/figure/p.trans_eQTL.flipped.png", height = 10, width = 10) 

### check to see the rate of different vs same subgenome trans-regulators 
eQTL %>% colnames() 
eQTL$eQTL_subgenome <- gsub("(A|C)([[:digit:]]+)", "\\1", eQTL$eQTL_chr)
eQTL$gene_subgenome <-  gsub("(A|C)([[:digit:]]+)", "\\1", eQTL$gene_CHROM)

sum(eQTL$eQTL_subgenome == eQTL$gene_subgenome) /nrow(eQTL) # 72% from the same subgenome 

A_genes <- eQTL[eQTL$eQTL_subgenome == "A",] 
sum(A_genes$eQTL_subgenome == A_genes$gene_subgenome) /nrow(A_genes) # 74% 

C_genes <- eQTL[eQTL$eQTL_subgenome == "C",] 
sum(C_genes$eQTL_subgenome == C_genes$gene_subgenome) /nrow(C_genes) # 70%  

# number of eQTL on A & C subgenome 
eQTL[eQTL$eQTL_subgenome == "A",] %>% nrow() /nrow(eQTL) 
eQTL[eQTL$eQTL_subgenome == "C",] %>% nrow() /nrow(eQTL) 
``` 

### find overlaps between eQTL and traitQTL 
```{r}
# trait QTL using scanone result  
load("~/F2/output/QTL_analysis/traitQTL.annotated.flipped.Rdata")
load("~/F2/output/eQTL/cis_trans_result_new_flipped_C05C08.Rdata") 

cis_eQTL %>% dim() #  11587    15
trans_eQTL %>% dim() # 14657    15  
traitQTL.annotated %>% dim() # 18647    13 

traitQTL.annotated %>% colnames()
traitQTL.annotated %>% 
  group_by(trait, chrom) %>% 
  dplyr::summarise(count = n()) %>% 
  dim()

cis_eQTL.qtl.combined <- inner_join(cis_eQTL,traitQTL.annotated,by="gene_ID") 
cis_eQTL.qtl.combined %>% head()    
cis_eQTL.qtl.combined %>% dim() # 2165   27   

colnames(cis_eQTL.qtl.combined) 

cis_eQTL.qtl.combined.final <- 
cis_eQTL.qtl.combined %>% 
  mutate(eQTL_start = start.x, eQTL_end = end.x, QTL_start = start.y, QTL_end = end.y, eQTL_genetic_start = genetic_start.x, eQTL_genetic_end = genetic_end.x, QTL_genetic_start = genetic_start.y, QTL_genetic_end = genetic_end.y) %>% 
  dplyr::select(-c(start.x, end.x, start.y, end.y, genetic_start.x, genetic_end.x, genetic_start.y, genetic_end.y)) 

write.csv(cis_eQTL.qtl.combined.final, file = "~/F2/output/eQTL/cis_eQTL.qtl.combined.final.csv")   
  
# trans-eQTL overlap with trait QTL, use genetic interval as the interval for both trait QTL and eQTL  

traitQTL <-  
traitQTL.annotated %>%  
  group_by(trait, chrom, genetic_start, genetic_end, model, start, end) %>% 
  dplyr::summarise(count = n())  

trans_eQTL %>% colnames() 
trans_eQTL %>% head()
gff.trans_eQTL <- GRanges(seqnames = Rle(trans_eQTL$eQTL_chr),ranges = IRanges(start = trans_eQTL$genetic_start, end = trans_eQTL$genetic_end), names = trans_eQTL$gene_ID) 

traitQTL %>% colnames() 
gff.trait_qtl<- GRanges(seqnames = Rle(paste("chr", traitQTL$chrom, sep = "")),ranges = IRanges(start = traitQTL$genetic_start, end = traitQTL$genetic_end), trait = traitQTL$trait)   

# cis_eQTL.qtl.combined 
trans_candidate <- mergeByOverlaps(gff.trait_qtl, gff.trans_eQTL) 
trans_candidate %>% dim()  # 4022    4  
trans_candidate 

### add the rest of information from trans_eQTL & trait_QTL 
trans_candidate <- 
trans_candidate %>% 
  as.data.frame() %>% 
  mutate(chrom = gff.trait_qtl.seqnames, trait_genetic_start = gff.trait_qtl.start, trait_genetic_end = gff.trait_qtl.end, gene_ID = names, eQTL_chr = gff.trans_eQTL.seqnames, eQTL_genetic_start = gff.trans_eQTL.start, eQTL_genetic_end = gff.trans_eQTL.end) %>% 
  dplyr::select(chrom, trait_genetic_start, trait_genetic_end, trait, gene_ID, eQTL_chr, eQTL_genetic_start, eQTL_genetic_end) 

### annotate trans_eQTL 
load("~/Reference/B.napus/BnapusAnnotation.Rdata") 
BnapusAnnotation %>% colnames()

trans_candidate.final <- 
trans_candidate %>%  
  left_join(BnapusAnnotation, c("gene_ID" = "name")) %>% 
  mutate(trait_chrom = chrom.x, gene.chrom = chrom.y, gene.start = start, gene.end = end) %>% 
  dplyr::select(-c(chrom.x, chrom.y, start, end)) 

## get GO term for each gene
load("~/Reference/B.napus/napus_GO_combined.Rdata") # there is one colomn hiding... 

trans_candidate.final <- 
trans_candidate.final %>% 
  left_join(napus_GO_combined) 

trans_candidate.final %>% dim() # 4022 16 
trans_candidate.final$gene_ID %>% unique() %>% length() # 1972 
write.csv(trans_candidate.final, file = "~/F2/output/eQTL/trans_candidate.final.csv") 

### make some plot for several important genes 
# the two FAE 

# the two 
### make some table & plot for several important genes 
# 1) Fatty acid/flowering/growth related genes for cis-eQTL final list 
cis_eQTL.qtl.combined.final_fatty_acid <- 
cis_eQTL.qtl.combined.final[grep("lipid|fatty", cis_eQTL.qtl.combined.final$GO_des),] %>% 
    dplyr::select(gene_ID, trait.y, AGI, At_symbol, GO_des) 

# 2) transcription factor coding genes for cis-eQTL final list
cis_eQTL.qtl.combined.final_TF <- 
cis_eQTL.qtl.combined.final[grep("DNA|nucleotide|transcription", cis_eQTL.qtl.combined.final$GO_des),] %>% 
  dplyr::select(gene_ID, trait.y, AGI, At_symbol, GO_des) 

# 3) Fatty acid/flowering/growth related genes for trans-eQTL final list
trans_candidate.final_fatty_acid <- 
trans_candidate.final[grep("lipid|fatty", trans_candidate.final$GO_des),] %>%
    dplyr::select(gene_ID, trait, AGI, At_symbol, GO_des) 

# 4) figures for the two cis-eQTL gene 
# BnaA08g11060D & BnaA08g11140D two cis-eQTL gene for fatty acid, need to deal with the color problem... more colors than a single palette can handel... 
# save(cis_eQTL.qtl.combined.final, trans_eQTL.qtl.combined.final, file = "~/F2/output/eQTL/eQTL.qtl.combined.final.Rdata") 

### check whether FLC is cis-regulator for some the traits 
# load("~/F2/output/eQTL/eQTL.qtl.combined.final.Rdata")

cis_eQTL.qtl.combined.final %>%  
  filter(AGI == "AT5G10140") %>% 
  View() # FLC is cis-regulator    

#### other important flower genes under C06? 
### important flower related genes 
flowering_time_gene <- read.csv("~/F2/for_paper/flowering_time/flowering_time_genes.csv")
flowering_time_gene$Gene.number <- gsub("\\ ", "", flowering_time_gene$Gene.number)
flowering_time_gene$Gene.number <- gsub("\\\xca", "", flowering_time_gene$Gene.number) 

cis_eQTL.qtl.combined.final_flowering <- 
cis_eQTL.qtl.combined.final[cis_eQTL.qtl.combined.final$AGI %in% flowering_time_gene$Gene.number,] %>% 
  dplyr::select(gene_ID, trait.y, AGI, At_symbol, GO_des) # no cis-flowering regulator under C06 

trans_candidate.final_flowering <- 
trans_candidate.final[trans_candidate.final$AGI %in% flowering_time_gene$Gene.number,] %>%
  dplyr::select(gene_ID, trait, AGI, At_symbol, GO_des)

write.csv(cis_eQTL.qtl.combined.final_fatty_acid, file = "~/F2/output/eQTL/cis_eQTL.qtl.combined.final_fatty_acid.csv")
write.csv(cis_eQTL.qtl.combined.final_flowering, file = "~/F2/output/eQTL/cis_eQTL.qtl.combined.final_flowering.csv")
write.csv(cis_eQTL.qtl.combined.final_TF, file = "~/F2/output/eQTL/cis_eQTL.qtl.combined.final_TF.csv")

write.csv(trans_candidate.final_fatty_acid, file = "~/F2/output/eQTL/trans_candidate.final_fatty_acid.csv")
write.csv(trans_candidate.final_flowering, file =  "~/F2/output/eQTL/trans_candidate.final_flowering.csv") 
```

### temp 
```{r}
eQTL %>% colnames() 
eQTL %>% 
  filter(gene_ID == "BnaC03g63040D" | gene_ID == "BnaC03g63070D" | gene_ID == "BnaC03g64150D") %>% 
  dplyr::select(gene_ID, eQTL_chr, pos, class, eQTL_subgenome, gene_subgenome) %>% 
  View()

eQTL %>% 
  filter(gene_ID == "BnaA08g11130D" | gene_ID == "BnaC03g65980D" | gene_ID == "BnaA08g11060D" | gene_ID == "BnaA08g11140D" | gene_ID == "BnaA08g12780D" | gene_ID == "BnaA08g27750D" | gene_ID == "BnaA10g22080D" | gene_ID == "BnaA04g09490D" | gene_ID == "BnaC06g29980D" | gene_ID == "BnaC09g26140D") %>% 
  dplyr::select(gene_ID, eQTL_chr, pos, class, eQTL_subgenome, gene_subgenome) %>% 
  View()    

eQTL %>% 
  filter(gene_ID == "BnaC09g26140D") %>% 
  dplyr::select(gene_ID, eQTL_chr, pos, class, eQTL_subgenome, gene_subgenome) %>% 
  View()  
```

