---
title: "one_map_simulate_data"
author: "Ruijuan Li"
date: "5/11/2017"
output: html_document
---

```{r}
library(onemap)
data("fake.f2.onemap")
fake.f2.onemap
twopts.f2 <- rf.2pts(fake.f2.onemap)
mark.all.f2 <- make.seq(twopts.f2, "all")
LGs.f2 <- group(mark.all.f2, LOD=3, max.rf=0.5)
LGs.f2

# genetic map of linkage group 2  
set.map.fun(type="haldane")
LG2.f2 <- make.seq(LGs.f2, 2)
LG2.f2

LG2.rcd.f2 <- rcd(LG2.f2)

LG2.f2.ord <- order.seq(input.seq=LG2.f2, n.init = 5,
                         subset.search = "twopt",
                         twopt.alg = "rcd", THRES = 3,
                         draw.try = TRUE, wait = 1)
LG2.f2.ord
LG2.f2.safe <- make.seq(LG2.f2.ord,"safe") 
(LG2.f2.all <- make.seq(LG2.f2.ord,"force"))

LG2.f2.ord <- order.seq(input.seq=LG2.f2, n.init = 5,
                         subset.search = "twopt",
                         twopt.alg = "rcd", THRES = 3,
                         draw.try = TRUE, wait = 1,
                         touchdown=TRUE) 
# touchdown: logical. If FALSE (default), the try.seq step is run only once, with the value of THRES. If TRUE, try.seq runs with THRES and then once more, with THRES-1. The latter calculations take longer, but usually are able to map more markers.  

(LG2.f2.final<-make.seq(LG2.f2.ord, "force"))
ripple.seq(LG2.f2.final, ws=5, LOD=3) 

LG2.f2.final

# linkage group 1 
LG1.f2 <- make.seq(LGs.f2, 1)

LG1.f2.ord <- order.seq(input.seq=LG1.f2, n.init = 5,
                         subset.search = "twopt",
                         twopt.alg = "rcd", THRES = 3,
                         draw.try = TRUE, wait = 1,
                         touchdown=TRUE)

(LG1.f2.final <- make.seq(LG1.f2.ord,"force"))

ripple.seq(ws=5, LG1.f2.final)

# linage group 3 
LG3.f2 <- make.seq(LGs.f2, 3)

LG3.f2.ord <- order.seq(input.seq=LG3.f2, n.init = 5,
                         subset.search = "twopt",
                         twopt.alg = "rcd", THRES = 3,
                         draw.try = TRUE, wait = 1,
                         touchdown=TRUE)

(LG3.f2.final <- make.seq(LG3.f2.ord,"force"))
test <- ripple.seq(ws=5, LG3.f2.final)

# with arbitrary order 
LG3seq.f2 <- make.seq(twopts.f2,c(47,38,59,16,62,21,20,48,22))
(LG3seq.f2.map <- map(LG3seq.f2))
marker.type(LG3seq.f2.map)
# add or drop marker 
(LG3seq.f2.map <- add.marker(LG3seq.f2.map, c(18,56,50)))
# drop marker 
(LG3seq.f2.map <- drop.marker(LG3seq.f2.map, c(59,21)))

# plot rf matrix 
temp.seq<-drop.marker(LG3.f2.final, 38) 
(temp.seq<-add.marker(temp.seq, 38)) # place marker 38 to the end of the map 
(LG3.f2.wrong<-map(temp.seq))

rf.graph.table(LG3.f2.wrong)

temp.seq <- drop.marker(LG3.f2.wrong,38)
temp.map <- map(temp.seq)
temp.try <- try.seq(temp.map, 38, draw.try=TRUE)
(LG3.f2.final<-make.seq(temp.try, 4))  

maps.list<-list(LG1.f2.final, LG2.f2.final, LG3.f2.final)
draw.map(maps.list, names= TRUE, grid=TRUE, cex.mrk=0.7)
draw.map(LG1.f2.final, names= TRUE, grid=TRUE, cex.mrk=0.7)
write.map(maps.list, "~/Desktop/Brassica_project/KIAT_RNA_seq/F2/output/fake.f2.onemap.map")
```

### for QTL analysis 
```{r}
raw.file<-paste(system.file("example",package="onemap"),
                "fake.f2.onemap.raw", sep="/")
raw.file 
fake.f2.qtl <- read.cross("mm", file=raw.file, mapfile="~/Desktop/Brassica_project/KIAT_RNA_seq/F2/output/fake.f2.onemap.map")
newmap <- est.map(fake.f2.qtl, tol=1e-6, map.function="kosambi")
plot.map(fake.f2.qtl, newmap)
fake.f2.qtl <- calc.genoprob(fake.f2.qtl, step=2)
out.em <- scanone(fake.f2.qtl, method="em")
out.hk <- scanone(fake.f2.qtl, method="hk")
plot(out.em, out.hk, col=c("blue","red"))
```

