---
title: "trans_eQTL_hostpot"
output: html_document
---

Purpose of this script is to identify trans-eQTL hotspot 

### practice 
```{r}
library(qtlhot)

ncross1 <- sim.null.cross(chr.len = rep(100, 4), 
n.mar = 51,
n.ind = 100,
type = "bc",
n.pheno = 1000,
latent.eff = 3,
res.var = 1,
init.seed = 123457) 

ncross1
cross1 <- include.hotspots(cross = ncross1,
hchr = c(2, 3, 4), 
hpos = c(25, 75, 50),
hsize = c(100, 50, 20),
Q.eff = 2,
latent.eff = 3,
lod.range.1 = c(2.5, 2.5),
lod.range.2 = c(5, 8),
lod.range.3 = c(10, 15),
res.var = 1,
n.phe = 1000,
init.seed = 12345)

cross1

ncor1 <- cor(cross1$pheno)
summary(ncor1[lower.tri(ncor1)])

rm(ncor1)
?rm

set.seed(123)
pt <- scanone(ncross1, method = "hk", n.perm = 1000)
alphas <- seq(0.01, 0.10, by=0.01)
lod.thrs <- summary(pt, alphas) # get lod thrs from scanone result for different alpha 
lod.thrs

lod.thr <- lod.thrs[5]
lod.thr # 95% as the threhold 

scan1 <- scanone(cross1, pheno.col = 1:1000, method = "hk")
scan1 %>% dim() # 204 1002 

high1 <- highlod(scan1, lod.thr = min(lod.thrs), drop.lod = 1.5)
high1 %>% names()
high1[[1]] %>% head(100) # LOD support interval for significant peaks for each trait 
high1[[2]] %>% dim() # marker information 
high1[[3]] # number of permutations 

max(high1, lod.thr = lod.thrs) #  maximum hotspot size for each possible single trait threshold, max.N is the number of traits out of 1000 pheno traits  

hots1 <- hotsize(high1, lod.thr = lod.thr) # for each genomic position, we count the number of traits that map to it with a LOD score equal or higher than the threshold in lod.thr.
summary(hots1) # 

plot(hots1, cex.lab = 1.5, cex.axis = 1.5) # plot the hotspot architecture inferred using the single trait permutation threshold 2.44 
lod.thr # 2.44 

# perform permutation tests to assess the statistical significance of the hotspots detected, hotperm uses NL & N method for permutation, Q method is implemented in ww.perm().  
set.seed(12345) 
hotperm1 <- hotperm(cross = cross1,
n.quant = 300,  # The parameter n.quant sets the maximum hotspot size to be analyzed 
n.perm = 100, # number of permutation 
lod.thrs = lod.thrs, # vector of LOD thresholds 
alpha.levels = alphas, # vector of significance levels  
drop.lod = 1.5, # LOD drop amount for support intervals 
verbose = FALSE) 
?hotperm # conduct NL & N permutation test,  
alphas 

hotperm1 
names(hotperm1)
summary(hotperm1)

hotperm1$max.N %>% dim() 
# max.N element of the hotperm1 object stores the output of the N-method’s permutations and is given by a matrix with 100 rows representing the permutations, and 10 columns representing the QTL mapping thresholds
hotperm1$max.N %>% head()

hotperm1$max.lod.quant %>% dim() # 100 300 # 100 rows representing the permutations, and 300 columns representing the hotspot sizes analyzed
hotperm1$max.lod.quant[1:10, 1:10] 

quant1 <- quantile(hotperm1, 0.05, lod.thr = lod.thr)
plot(high1, quant.level = quant1, sliding = TRUE)
summary(hotperm1)

hotsq1 <- hotsize(high1, lod = lod.thr, window = 5, quant.level = quant1)
plot(hotsq1)
summary(hotsq1)

### example with uncorrelated phenotypes 
ncross2 <- sim.null.cross(chr.len = rep(100,4),
n.mar = 51,
n.ind = 100,
type = "bc",
n.phe = 1000,
latent.eff = 0,
res.var = 1,
init.seed = 123457)

cross2 <- include.hotspots(cross = ncross2,
hchr = c(2, 3, 4),
hpos = c(25, 75, 50),
hsize = c(100, 50, 20),
Q.eff = 2,
latent.eff = 0,
lod.range.1 = c(2.5, 2.5),
lod.range.2 = c(5, 8),
lod.range.3 = c(10, 15),
res.var = 1,
n.phe = 1000,
init.seed = 12345)

ncor2 <- cor(cross2$pheno)
summary(ncor2[lower.tri(ncor2)])

rm(ncor2)
scan2 <- scanone(cross2, pheno.col = 1:1000, method = "hk")
high2 <- highlod(scan2, lod.thr = lod.thr, drop.lod = 1.5)

hots2 <- hotsize(high2)
plot(hots2, cex.lab = 1.5, cex.axis = 1.5)

set.seed(12345)

hotperm2 <- hotperm(cross = cross2,
n.quant = 300,
n.perm = 100,
lod.thrs = lod.thrs,
alpha.levels = alphas,
drop.lod = 1.5,
verbose = FALSE)

quant2 <- quantile(hotperm2, 0.05, lod.thr = lod.thr)
quant2

plot(high2, lod.thr = lod.thr, quant.level = quant2, sliding = TRUE)
plot(high2, quant.level = quant2)
### still several points not very clear, especially how permutation works here... 
``` 

### using N method for trans-eQTL hotspot identification 
```{r}
library(tidyverse)
library(qtl)
library(qtlhot)

load("~/F2/output/eQTL/scanone-eqtl_F2_flipped.RData") 
scanone_eQTL.F2 %>% dim() # 4887 56182 

scanone_eQTL.F2[1:10, 1:10]

### extract genes with trans-eQTL only 
load("~/F2/output/eQTL/cis_trans_result_new_flipped.Rdata") 

cis_eQTL %>% dim() # 11384    12
trans_eQTL %>% dim() # 15197    12  

# include genes with trans-eQTL only  
cis_eQTL %>% head  
cis_eQTL$gene_ID %>% unique() %>% length()
trans_eQTL$gene_ID %>% unique() %>% length() # 13296 
length(cis_eQTL$gene_ID[cis_eQTL$gene_ID %in% trans_eQTL$gene_ID]) # 1814 genes not only have cis-eQTL, but also have trans-eQTL 

scanone_eQTL.F2.trans <- scanone_eQTL.F2[,(colnames(scanone_eQTL.F2) %in% c("chr", "pos", trans_eQTL$gene_ID))]
cbind(pos, scanone_eQTL.F2.trans) %>% dim() 

dim(scanone_eQTL.F2.trans) # 4887 13298
scanone_eQTL.F2.trans[1:10, 1:10]
scanone_eQTL.F2[1:10, 1:10]
### check correlation, later... 
cross.F2
lod.thrs
alphas <- seq(0.01, 0.10, by=0.01)  

### LOD threshold level for e-trait 
lod.thr <- lod.thrs[5]
lod.thr 

### get cross.F2 for trans-eQTL only 
cross.F2$pheno <- cross.F2$pheno[,(colnames(cross.F2$pheno) %in% c(trans_eQTL$gene_ID))]

### get only significant intervals for each e-trait, using LOD drop method, understand the threhsold here 
high1 <- highlod(scanone_eQTL.F2.trans, lod.thr = min(lod.thrs), drop.lod = 1.5) 
max(high1, lod.thr = lod.thrs) # max number of e-trait fall into loci with different lod threshold   

hots1 <- hotsize(high1, lod.thr = lod.thr)  
summary(hots1) # for each genomic position 

### permutation to get the statistical significance # permutation takes time, did this in screen 
# trans_eQTL_hotspot_perm_trans.R 

load("~/F2/output/eQTL/hotperm1.trans.Rdata")
hotperm1.trans   

png("~/F2/output/QTL_analysis/figure/trans_eQTL_hotspot.png", width=15, height=10, units="in", res=300) 
plot(hots1, cex.lab = 1.5, cex.axis = 1.5) 
abline(h = 129) 
dev.off()

### how to get all the genetic pos with trans-eQTL hotspot? 
hot_trans <- data.frame(chr = hots1$chr,
                        pos = hots1$pos,
                        max.N = hots1$max.N)

hot_trans <- 
hot_trans %>% 
  filter(max.N > 129) %>% 
  mutate(eQTL_chr = chr) 

trans_eQTL %>% colnames()
hot_trans

### hotspot 
# A01: 128-129
# A01: 160-164
# A02: 0-9
# A03: 17-25
# A03: 36-38
# A03: 43
# A03: 49-64
# A06: 122-124
# A09: 17-19 
# A10: 173-185
# A10: 217-226
# C01: 156-166
# C02: 1-13
# C02: 43-62
# C03: 10-24
# C04: 97
# C08: 40-41
# C08: 47-62
# C09: 0-4
# C09: 57-60 

hotspot <- data.frame(chr = c("A01", "A01", "A02", "A03", "A03", "A03", "A03", "A06", "A09", "A10", "A10", "C01", "C02", "C02", "C03", "C04", "C08", "C08", "C09", "C09"), 
                      pos_min = c(128, 160, 0, 17, 36, 43, 49, 122, 17, 173, 217, 156, 1, 43, 10, 97, 40, 47, 0, 57), 
                      pos_max = c(129, 164, 9, 25, 38, 43, 64, 124, 19, 185, 226, 166, 13, 62, 24, 97, 41, 62, 4, 60))

hotspot$chr <- paste("chr", hotspot$chr, sep = "")  
hotspot$hotspot_id <- rownames(hotspot)

### GO enrichment of trans-eQTL hotspot regulated genes 
hot_trans$eQTL_chr <- paste("chr", hot_trans$eQTL_chr, sep = "")

hot_trans %>% colnames()

trans_eQTL_hot <- 
trans_eQTL %>% 
  semi_join(hot_trans, by = c("eQTL_chr", "pos")) 

dim(trans_eQTL_hot) # 4221 12 

trans_eQTL_genes <- GRanges(seqnames = Rle(trans_eQTL_hot$eQTL_chr),ranges = IRanges(start = trans_eQTL_hot$pos, end = trans_eQTL_hot$pos), names = trans_eQTL_hot$gene_ID)
trans_eQTL_genes 

hotspots <- 
lapply(1:nrow(hotspot), function(i) {
  GRanges(seqnames = Rle(hotspot$chr[i]), ranges = IRanges(start = hotspot$pos_min[i], end = hotspot$pos_max[i]), ID = hotspot$hotspot_id[i])
})

trans_eQTL_genes_list <- 
lapply(1:length(hotspots), function(i) 
  mergeByOverlaps(trans_eQTL_genes, hotspots[[i]])$names
)

length(trans_eQTL_genes_list) # 20 

### BnaA08g11130D (FAE) & BnaC03g65980D (FAE) are regulated by A03 trans-eQTL hostpot, the two BnaA.FAE1 reported by other people       
```  

### GO enrichment of trans-eQTL hotspot regulated genes 
```{r}
load("~/Desktop/F2_paper/data/trans_eQTL_genes_list.Rdata")
source("~/Desktop/Brassica_project/KIAT_RNA_seq/analysis/function_BnRNAseq.R")  

GO_trans_eQTL <- 
lapply(1:length(trans_eQTL_genes_list), function(i) {
  tryCatch(
    GOseq.Bn.ORA(trans_eQTL_genes_list[[i]]), error= function(e) NA)
})

GO_trans_eQTL 
save(GO_trans_eQTL, file = "~/Desktop/F2_paper/data/GO_trans_eQTL.Rdata")
```

